spring:
  datasource:
    url: jdbc:mysql://39.108.50.130/easyaution_pms?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.108.50.130
    port: 6379
  profiles:
    active: local #将密码配置到这个文件中，不上传到git
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #指定日期格式输出
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #使用自增组件
      logic-delete-value: 0
      logic-not-delete-value: 1