kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: node编译
    image: node:10.18.1-alpine3.9
    commands:
      - npm config set registry https://registry.npm.taobao.org/
      - npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
      - npm install
      - npm run build:prod

  - name: 构建
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      insecure: true
      username: 韦fufa
      password: aliyun123456
      registry:  registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/weifufa/easy_admin_vue
      tags: 1.0.0

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
