spring:
  datasource:
    username: 'root'
    password: "wff123456..."
    url: jdbc:mysql://39.108.50.130:3306/easyaution_ums?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 39.108.50.130
    password: 123456
    port: 6379