spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: https://miitangs09.market.alicloudapi.com
        path: /v1/tools/sms/code/sender
        smsSignId: "0000"
        smsTemplateNo: #模板
        appcode: 45bc08b803c84e47bf7ae93903e68301
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: wff-auction-bucket

  profiles:
    active: local #将密码配置到这个文件中，不上传到git